name: here_bro
description: "Locate your bro with a NOTIFICATION"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  firebase_auth: ^6.1.2
  firebase_core: ^4.3.0
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/HereBro.png
